### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by KalliopiPliogka**
Fixed bill message. Now, bill message is showing without the bill number.

### CODE REVIEW

**Comment by abouolia** [comment]
@KalliopiPliogka Wonderful, Could you please remove the injected number value where these keywords being used. like used in `BillForm.tsx`.

**Review by abouolia — APPROVED** [review]

**Comment by KalliopiPliogka** [comment]
I looked for references of these keywords in the rest of the project but i only found in `BillForm.tsx` as you pointed out.
So, i fixed that.
If there are any other references of these keywords let me know.

**Comment by abouolia** [comment]
@all-contributors please add @KalliopiPliogka  for bug

**Comment by abouolia** [comment]
@KalliopiPliogka Thanks for your contribution we're appreciate that, I added you to contributors list hope keep contribute more to project.

**Pull request merged**
