### PR TITLE
fix: Expense cannot accept credit card as payment account

### PR DESCRIPTION
**Pull request by abouolia**

### CODE REVIEW

**Comment by sbsroc** [comment]
Thank you for working on this. For some reason my credit card is not in the payment dropdown yet, and I just pulled the new version down. I performed a hard browser refresh - Shift F5, added a new Credit Card account. Neither the old nor the new show as a dropdown option.
The release notes say that this was included 2 weeks ago. Did I do something wrong?
Thanks!

**Comment by abouolia** [comment]
When you created Credit Card account from accounts chart, did you select Credit Card as a type for the account? Or you created the account from another place. @sbsroc

**Comment by sbsroc** [comment]
> When you created Credit Card account from accounts chart, did you select Credit Card as a type for the account? Or you created the account from another place. @sbsroc

Yes, both have "Credit Card" as the account type. I have "Chase Ink" and "Test" in the list.

I'm pretty sure I updated. How do I tell which version of Bigcapital I'm running? Is it in the UI somewhere?

**Comment by abouolia** [comment]
weird, unfortunately showing the current version something would like to do, you can follow the upgrade guide, when you docker compose pull if pulled new images that means your current images are not up-to-date. https://docs.bigcapital.app/deployment/docker#upgrading

**Comment by sbsroc** [comment]
I wrote a script to update it. It has almost no checks in it, but it works for me so far:

#!/bin/bash
cd /opt/bigcapital/
[ -f docker-compose.prod.yml ] || exit
docker-compose --file docker-compose.prod.yml stop
docker-compose --file docker-compose.prod.yml pull
docker-compose --file docker-compose.prod.yml up --build -d

**Comment by sbsroc** [comment]
I ran it again.
"docker ps" says that the Bigcapital containers were created 2 days ago.
I run watchtower on this LXC and it fails to update Bigcapital, so I do it manually. It's possible something is wrong with my image, but I'm not very skilled with docker (new to it this year). if I could remove the image and re-create it without losing my data, I'm all for it. The mysql container holds all data I presume so if I destroy all else and re-run pull and build, would that work?

**Pull request merged**
