### PR TITLE
feat: Update Docker Build-Push Action and Add ARM64 Support

### PR DESCRIPTION
**Pull request by cloudsbird**
Issues:  https://github.com/bigcapitalhq/bigcapital/issues/296
This pull request introduces two significant changes to our Docker build and push workflow:

Update:
- Docker Build-Push Action Version: The version of docker/build-push-action has been updated from v2 to v5.
- Add ARM64 Platform Support: Previously, our Docker images were only built for the linux/amd64 platform. With this update, we are adding support for the linux/arm64 platform. 
- Docker Login Action Version : The version of docker/login-action has been updated from v1 to v3

References:
https://docs.docker.com/build/ci/github-actions/multi-platform/

### CODE REVIEW

**Review by abouolia — APPROVED** [review]
Everything is perfect.

**Comment by abouolia** [comment]
@cloudsbird  Really appreciate your contribution, one of the things we wanted to add to this GH action, pushing Docker containers by version tag instead of `latest` to keep all versions in the Docker registry and make it easy to users to rollback to the previous versions. @all-contributors please add @cloudsbird code

**Comment by abouolia** [comment]
@all-contributors please add @cloudsbird code

**Comment by cloudsbird** [comment]
hi @abouolia, 
Okay I will create issues for this

**Pull request merged**
